# Generated by Django 5.0.3 on 2024-03-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('subtitle', models.CharField(max_length=254)),
                ('instrumentation', models.CharField(max_length=254)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
