# Generated by Django 5.0.3 on 2024-03-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='instrumentation',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='composition',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='composition',
            name='subtitle',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
