# Generated by Django 5.0.3 on 2024-03-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compositions", "0002_alter_composition_instrumentation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="premiere_date",
            field=models.DateField(blank=True, default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="composition",
            name="year",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
