# Generated by Django 5.0.3 on 2024-03-28 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0003_composition_premiere_date_composition_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='premiere_date',
        ),
    ]
