# Generated by Django 5.0.3 on 2024-04-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0004_remove_composition_premiere_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='publisher',
            new_name='category',
        ),
        migrations.AddField(
            model_name='composition',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
