# Generated by Django 5.0.3 on 2024-04-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0005_rename_publisher_composition_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
