# Generated by Django 5.0.3 on 2024-04-02 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0006_alter_composition_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 22, 54, 19, 986468)),
        ),
    ]
